//! Rules engine types: declarative match/action rules inspired by Cloudflare
//! Custom Rules / WAF.
//!
//! Rules are evaluated **before** heuristics and AI, as a fast path. An
//! `Allow` rule short-circuits the whole pipeline (allowlist); a `Block` /
//! `Challenge` / `RateLimit` rule short-circuits with the corresponding
//! action; `Log` / `Tag` rules annotate the event and let it flow.
//!
//! Rules come from three sources: static config, the dynamic `rules` table
//! in Postgres (hot-reloaded via LISTEN/NOTIFY), and reputation feeds.

use std::collections::HashMap;
use std::net::IpAddr;
use std::sync::{Arc, LazyLock, RwLock};
use std::time::Duration;

use chrono::{DateTime, Utc};
use ipnet::IpNet;
use regex::Regex;
use serde::{Deserialize, Serialize};

use crate::analysis::Verdict;
use crate::event::{Event, HttpMethod, ProtocolKind};
use crate::ratelimit::RateLimitBackend;

pub mod dsl;

/// Process-lifetime regex cache for rule patterns (F5).
///
/// Compiling a `Regex` costs hundreds of microseconds; the old code did it
/// per rule per event, dominating the pipeline at ~3 ms/event. Rules are
/// user-defined (config/DB/feeds) and finite, so the cache is bounded by the
/// ruleset size and never sees attacker-controlled input.
static REGEX_CACHE: LazyLock<RwLock<HashMap<String, Option<Arc<Regex>>>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

/// Compiled-or-invalid regex by pattern. `None` = pattern failed to compile
/// (cached so broken rules don't re-parse on every event).
fn cached_regex(pattern: &str) -> Option<Arc<Regex>> {
    let hit = REGEX_CACHE
        .read()
        .ok()
        .and_then(|c| c.get(pattern).cloned());
    if let Some(cached) = hit {
        return cached;
    }
    let compiled = Regex::new(pattern).ok().map(Arc::new);
    if let Ok(mut c) = REGEX_CACHE.write() {
        c.insert(pattern.to_string(), compiled.clone());
    }
    compiled
}

/// A parsed IP specification (CIDR / single / range).
#[derive(Debug, Clone, Copy)]
enum IpSpec {
    Net(IpNet),
    Single(IpAddr),
    Range(IpAddr, IpAddr),
}

impl IpSpec {
    fn contains(&self, ip: IpAddr) -> bool {
        match *self {
            IpSpec::Net(n) => n.contains(&ip),
            IpSpec::Single(s) => s == ip,
            IpSpec::Range(a, b) => ip_in_range(ip, a, b),
        }
    }
}

/// Process-lifetime cache of parsed IP specs (F5) — `spec.parse::<IpNet>()`
/// per rule per event was measurable on CIDR-heavy packs (vpn_proxy, tor).
static IP_CACHE: LazyLock<RwLock<HashMap<String, Option<IpSpec>>>> =
    LazyLock::new(|| RwLock::new(HashMap::new()));

fn cached_ip_spec(spec: &str) -> Option<IpSpec> {
    let hit = IP_CACHE.read().ok().and_then(|c| c.get(spec).copied());
    if let Some(cached) = hit {
        return cached;
    }
    let parsed = parse_ip_spec(spec);
    if let Ok(mut c) = IP_CACHE.write() {
        c.insert(spec.to_string(), parsed);
    }
    parsed
}

fn parse_ip_spec(spec: &str) -> Option<IpSpec> {
    if let Ok(net) = spec.parse::<IpNet>() {
        return Some(IpSpec::Net(net));
    }
    if let Ok(single) = spec.parse::<IpAddr>() {
        return Some(IpSpec::Single(single));
    }
    let (a, b) = spec.split_once('-')?;
    let a = a.trim().parse::<IpAddr>().ok()?;
    let b = b.trim().parse::<IpAddr>().ok()?;
    Some(IpSpec::Range(a, b))
}

/// Stable identifier for a rule.
pub type RuleId = String;

/// Where a rule came from — useful for the CLI (`rules list --source db`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RuleSource {
    /// Defined in `sentry.toml`.
    Config,
    /// Created via CLI / dashboard, stored in Postgres.
    Db,
    /// Synced from a Cloudflare account.
    CloudflareSync,
    /// Generated by the reputation feed importer.
    Feed,
    /// Auto-learned from a confirmed incident (auto-block with TTL).
    AutoLearned,
    /// Built-in default rule pack.
    DefaultPack,
}

/// What a rule does when it matches.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RuleAction {
    /// Bypass scoring and AI entirely — the IP/ASN/path is trusted.
    Allow,
    /// Block the request / IP.
    Block,
    /// Issue a Cloudflare challenge.
    Challenge,
    /// Apply rate limiting (parameters carried on the rule).
    RateLimit,
    /// Only record the match; let the event continue through the pipeline.
    Log,
    /// Attach a tag to the event; continue.
    Tag,
}

impl From<RuleAction> for Verdict {
    fn from(a: RuleAction) -> Self {
        match a {
            RuleAction::Allow => Verdict::Allow,
            RuleAction::Block => Verdict::Block,
            RuleAction::Challenge => Verdict::Challenge,
            RuleAction::RateLimit => Verdict::RateLimit,
            RuleAction::Log | RuleAction::Tag => Verdict::Allow,
        }
    }
}

/// A single rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Rule {
    /// Stable id (slug or uuid).
    pub id: RuleId,
    /// Human-readable name.
    pub name: String,
    /// Lower number = evaluated first.
    pub priority: i32,
    /// Whether the rule is active.
    pub enabled: bool,
    /// Condition that triggers the rule.
    pub match_: RuleMatch,
    /// Action to take on match.
    pub action: RuleAction,
    /// TTL for dynamic rules (auto-expire). `None` = permanent.
    pub ttl: Option<Duration>,
    /// Origin of the rule.
    pub source: RuleSource,
    /// Free-form tags for grouping/inspection (`vpn`, `crawler`, …).
    pub tags: Vec<String>,
    /// When the rule was created (for DB/feed rules).
    pub created_at: Option<DateTime<Utc>>,
}

/// A compiled, indexable set of rules ready for evaluation.
///
/// Wraps rules in `Arc<RwLock>` so the daemon can hot-swap the set without
/// restarting when Postgres notifies of changes. Evaluation indexes rules
/// by IP / ASN / country for fast lookup instead of linear scan.
#[derive(Debug, Default, Clone)]
pub struct RuleSet {
    /// Rules sorted by priority ascending.
    rules: Vec<Rule>,
}

/// A hot-reloadable handle to a [`RuleSet`].
///
/// The daemon holds this as `Arc<RwLock<RuleSet>>` and the hot-reload
/// task swaps the inner set via `write()`. Evaluation acquires a `read()`
/// lock — cheap because evaluation is fast (microseconds).
pub type SharedRuleSet = Arc<RwLock<RuleSet>>;

/// Create a [`SharedRuleSet`] from a [`RuleSet`].
pub fn shared(ruleset: RuleSet) -> SharedRuleSet {
    Arc::new(RwLock::new(ruleset))
}

impl RuleSet {
    /// Build a ruleset from an unsorted collection of rules.
    pub fn new(mut rules: Vec<Rule>) -> Self {
        rules.sort_by_key(|r| r.priority);
        Self { rules }
    }

    /// Number of rules in the set.
    pub fn len(&self) -> usize {
        self.rules.len()
    }

    /// Whether the set is empty.
    pub fn is_empty(&self) -> bool {
        self.rules.is_empty()
    }

    /// Append rules (e.g. generated feed rules) and re-sort by priority.
    pub fn extend(&mut self, rules: impl IntoIterator<Item = Rule>) {
        self.rules.extend(rules);
        self.rules.sort_by_key(|r| r.priority);
    }

    /// Iterate over rules in evaluation order.
    pub fn iter(&self) -> impl Iterator<Item = &Rule> {
        self.rules.iter()
    }

    /// Evaluate the ruleset against an event.
    ///
    /// Returns the first matching rule's action (short-circuit) along with
    /// the rule id, or `None` if no rule matched. `Allow` rules also
    /// short-circuit (they bypass the rest of the pipeline).
    pub fn evaluate(&self, evt: &Event) -> Option<(&Rule, bool)> {
        self.evaluate_with(evt, None)
    }

    /// Evaluate with a rate-limit backend for `RuleMatch::Rate` conditions.
    ///
    /// Without a backend, `Rate` conditions never match (same as
    /// [`evaluate`](Self::evaluate)).
    pub fn evaluate_with(
        &self,
        evt: &Event,
        backend: Option<&dyn RateLimitBackend>,
    ) -> Option<(&Rule, bool)> {
        for rule in &self.rules {
            if !rule.enabled {
                continue;
            }
            if rule.match_.matches_with(evt, backend) {
                // Allow and Block/Challenge/RateLimit short-circuit;
                // Log/Tag continue to the next rule after annotating.
                let short_circuit = matches!(
                    rule.action,
                    RuleAction::Allow
                        | RuleAction::Block
                        | RuleAction::Challenge
                        | RuleAction::RateLimit
                );
                return Some((rule, short_circuit));
            }
        }
        None
    }
}

/// Declarative match expression. Combinable with `All`/`Any`/`Not`.
///
/// The DSL parser (`sentry-core::rules::dsl`, future) translates the textual
/// `match = 'ip=10.0.0.0/8 AND path regex "\\.env"'` form into this enum.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RuleMatch {
    /// Match a specific IP, CIDR or range.
    Ip {
        /// IP literal, CIDR (`10.0.0.0/8`) or range (`10.0.0.1-10.0.0.99`).
        cidr: String,
    },
    /// Match an Autonomous System Number.
    Asn(u32),
    /// Match a country (ISO 3166-1 alpha-2).
    Country(String),
    /// Match the request path.
    Path {
        /// Match operator.
        op: PathOp,
        /// Pattern.
        pattern: String,
    },
    /// Match the HTTP method.
    Method(HttpMethod),
    /// Match a header by name + operator.
    Header {
        /// Header name (case-insensitive).
        name: String,
        /// Match operator.
        op: StrOp,
    },
    /// Match the User-Agent.
    UserAgent(StrOp),
    /// Match the query string.
    Query(StrOp),
    /// Match request body bytes (when available).
    Body(StrOp),
    /// Match the coarse protocol kind.
    Protocol(ProtocolKind),
    /// Match a TLS fingerprint.
    TlsFingerprint {
        /// JA3 hash.
        ja3: Option<String>,
        /// JA4 hash.
        ja4: Option<String>,
    },
    /// Match a reputation tier assigned to the client IP.
    Reputation(ReputationTier),
    /// Match the HTTP response status code.
    Status(u16),
    /// Match a rate condition (count over window).
    Rate {
        /// Number of events.
        count: u32,
        /// Window duration in seconds.
        per_secs: u64,
        /// Scope of the rate check.
        scope: RateScope,
    },
    /// Time-of-day window.
    Time {
        /// Window spec (parsed externally).
        window: TimeWindow,
    },
    /// Logical AND of sub-matches.
    All(Vec<RuleMatch>),
    /// Logical OR of sub-matches.
    Any(Vec<RuleMatch>),
    /// Logical NOT of a sub-match.
    Not(Box<RuleMatch>),
}

/// Path match operator.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum PathOp {
    /// Exact match.
    Equals,
    /// Glob match (`/admin/*`).
    Glob,
    /// Regex match.
    Regex,
    /// Starts with.
    StartsWith,
}

/// String match operator.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum StrOp {
    /// Exact equality.
    Equals {
        /// Value to compare against.
        value: String,
    },
    /// Substring containment.
    Contains {
        /// Substring to find.
        value: String,
    },
    /// Regex match.
    Regex {
        /// Regex pattern.
        pattern: String,
    },
    /// Prefix match.
    StartsWith {
        /// Prefix to require.
        value: String,
    },
    /// Match against any of a set of values.
    In {
        /// Accepted values.
        values: Vec<String>,
    },
}

/// Reputation tier assigned to a client IP by the geo/reputation layer.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ReputationTier {
    /// No reputation data.
    Unknown,
    /// Known-good (allowlisted feed).
    Clean,
    /// Mildly suspicious.
    Suspicious,
    /// Confirmed malicious (in a blocklist feed).
    Malicious,
    /// Hosting provider / datacenter IP (bot-prone).
    Datacenter,
    /// VPN / commercial proxy.
    VpnProxy,
    /// Tor exit node.
    Tor,
}

impl ReputationTier {
    /// Parse a tier name as used in config and the rule DSL
    /// (`tor`, `vpn`, `malicious`, …). Accepts the aliases understood by the
    /// DSL for backwards compatibility.
    pub fn parse(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "unknown" => Some(Self::Unknown),
            "clean" | "allowlist" | "allowlisted" => Some(Self::Clean),
            "suspicious" => Some(Self::Suspicious),
            "malicious" | "blocklist" | "blocklisted" | "bad" => Some(Self::Malicious),
            "datacenter" | "hosting" => Some(Self::Datacenter),
            "vpn" | "proxy" | "vpn_proxy" | "vpnproxy" => Some(Self::VpnProxy),
            "tor" => Some(Self::Tor),
            _ => None,
        }
    }
}

/// Scope of a rate check.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RateScope {
    /// Per client IP.
    PerIp,
    /// Per ASN.
    PerAsn,
    /// Per path.
    PerPath,
    /// Global.
    Global,
}

/// Time window spec (simplified — full cron-like parsing is future work).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TimeWindow {
    /// Active only inside this local time range, e.g. `09:00-18:00`.
    Inside {
        /// `HH:MM-HH:MM`.
        range: String,
        /// IANA timezone, e.g. `America/Sao_Paulo`.
        tz: String,
    },
    /// Active only outside this local time range.
    Outside {
        /// `HH:MM-HH:MM`.
        range: String,
        /// IANA timezone.
        tz: String,
    },
}

impl RuleMatch {
    /// Evaluate the match against an event.
    ///
    /// Kept deliberately straightforward: this is the fast path, so we avoid
    /// heap allocation in the common "no match" case. Regexes and IP specs
    /// are compiled/parsed once per process (F5 caches); the URL-decoded path
    /// is computed once per evaluation, not once per path condition.
    pub fn matches(&self, evt: &Event) -> bool {
        self.matches_with(evt, None)
    }

    /// Evaluate with an optional rate-limit backend for `Rate` conditions.
    ///
    /// `Time` conditions still require wall-clock evaluation (future work)
    /// and never match here.
    pub fn matches_with(&self, evt: &Event, backend: Option<&dyn RateLimitBackend>) -> bool {
        let decoded_path = evt.http().map(|h| crate::rules::url_decode(&h.path));
        let ctx = EvalCtx {
            decoded_path: decoded_path.as_deref(),
        };
        self.matches_ctx(evt, backend, &ctx)
    }

    fn matches_ctx(
        &self,
        evt: &Event,
        backend: Option<&dyn RateLimitBackend>,
        ctx: &EvalCtx,
    ) -> bool {
        match self {
            Self::Ip { cidr } => match_ip(cidr, evt.client_ip),
            Self::Asn(asn) => evt.asn == Some(*asn),
            Self::Country(c) => evt
                .geo
                .as_ref()
                .and_then(|g| g.country.as_deref())
                .map(|cc| cc.eq_ignore_ascii_case(c))
                .unwrap_or(false),
            Self::Path { op, pattern } => ctx
                .decoded_path
                .map(|decoded| match_path(op, pattern, decoded))
                .unwrap_or(false),
            Self::Method(m) => evt
                .http()
                .and_then(|h| h.method)
                .map(|method| method == *m)
                .unwrap_or(false),
            Self::Header { name, op } => evt
                .http()
                .and_then(|h| {
                    h.headers
                        .iter()
                        .find(|(k, _)| k.eq_ignore_ascii_case(name))
                        .map(|(_, v)| v)
                })
                .map(|v| match_str_op(op, v))
                .unwrap_or(false),
            Self::UserAgent(op) => evt
                .http()
                .and_then(|h| h.user_agent.as_deref())
                .map(|ua| match_str_op(op, ua))
                .unwrap_or(false),
            Self::Query(op) => evt
                .http()
                .and_then(|h| h.query.as_deref())
                .map(|q| match_str_op(op, q))
                .unwrap_or(false),
            Self::Body(op) => evt
                .http()
                .and_then(|h| h.body.as_ref())
                .map(|b| {
                    let s = String::from_utf8_lossy(b);
                    match_str_op(op, &s)
                })
                .unwrap_or(false),
            Self::Protocol(p) => evt.protocol_kind() == *p,
            Self::TlsFingerprint { ja3, ja4 } => evt
                .tls()
                .map(|t| {
                    ja3.as_ref()
                        .zip(t.ja3.as_ref())
                        .map(|(a, b)| a == b)
                        .unwrap_or(false)
                        || ja4
                            .as_ref()
                            .zip(t.ja4.as_ref())
                            .map(|(a, b)| a == b)
                            .unwrap_or(false)
                })
                .unwrap_or(false),
            Self::Reputation(tier) => evt
                .reputation
                .as_ref()
                .map(|r| r.tier == *tier)
                .unwrap_or(false),
            Self::Status(code) => evt
                .http()
                .and_then(|h| h.status)
                .map(|s| s == *code)
                .unwrap_or(false),
            Self::Rate {
                count,
                per_secs,
                scope,
            } => {
                let Some(backend) = backend else {
                    return false;
                };
                let Some(key) = rate_scope_key(*scope, evt) else {
                    return false;
                };
                // Bucket identity includes the condition params so two rules
                // with identical thresholds share a counter, and different
                // thresholds stay independent.
                let key = format!("{key}:{count}/{per_secs}s");
                backend.record_and_check(&key, *count, *per_secs)
            }
            Self::Time { .. } => {
                // Time windows need wall-clock + timezone handling; future work.
                false
            }
            Self::All(items) => items.iter().all(|m| m.matches_ctx(evt, backend, ctx)),
            Self::Any(items) => items.iter().any(|m| m.matches_ctx(evt, backend, ctx)),
            Self::Not(inner) => !inner.matches_ctx(evt, backend, ctx),
        }
    }
}

/// Per-evaluation scratch shared by the whole match tree (F5): the decoded
/// path used by every `Path` condition, computed once.
struct EvalCtx<'a> {
    decoded_path: Option<&'a str>,
}

/// Build the backend key for a rate condition scope.
///
/// `PerAsn` returns `None` when the event has no ASN (never matches);
/// `PerPath` returns `None` for non-HTTP events.
fn rate_scope_key(scope: RateScope, evt: &Event) -> Option<String> {
    match scope {
        RateScope::PerIp => Some(format!("ip:{}", evt.client_ip)),
        RateScope::PerAsn => evt.asn.map(|a| format!("asn:{a}")),
        RateScope::PerPath => evt
            .http()
            .map(|h| format!("path:{}", h.path.to_ascii_lowercase())),
        RateScope::Global => Some("global".to_string()),
    }
}

/// Check whether `ip` is contained in `spec` (single IP, CIDR or range).
///
/// Specs are parsed once and cached (F5); invalid specs never match.
fn match_ip(spec: &str, ip: IpAddr) -> bool {
    cached_ip_spec(spec).is_some_and(|s| s.contains(ip))
}

/// Check whether `ip` falls between `lo` and `hi` (inclusive).
///
/// Only works for same-family addresses; returns `false` otherwise.
fn ip_in_range(ip: IpAddr, lo: IpAddr, hi: IpAddr) -> bool {
    match (ip, lo, hi) {
        (IpAddr::V4(x), IpAddr::V4(a), IpAddr::V4(b)) => {
            let x = u32::from(x);
            let a = u32::from(a);
            let b = u32::from(b);
            x >= a.min(b) && x <= a.max(b)
        }
        (IpAddr::V6(x), IpAddr::V6(a), IpAddr::V6(b)) => {
            let x = u128::from(x);
            let a = u128::from(a);
            let b = u128::from(b);
            x >= a.min(b) && x <= a.max(b)
        }
        _ => false,
    }
}

/// Percent-decode a URL component (same logic as heuristics).
///
/// Rule path matching runs on the decoded form so encoded payloads
/// (`%2e%2e%2f` = `../`) can't bypass rule matchers.
fn url_decode(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'+' => {
                out.push(b' ');
                i += 1;
            }
            b'%' if i + 2 < bytes.len() => {
                let hi = hex_val(bytes[i + 1]);
                let lo = hex_val(bytes[i + 2]);
                if let (Some(h), Some(l)) = (hi, lo) {
                    out.push((h << 4) | l);
                    i += 3;
                } else {
                    out.push(bytes[i]);
                    i += 1;
                }
            }
            b => {
                out.push(b);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn hex_val(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

/// Apply a path match operator on the already URL-decoded path.
fn match_path(op: &PathOp, pattern: &str, decoded: &str) -> bool {
    match op {
        PathOp::Equals => decoded == pattern,
        PathOp::Glob => glob_match(pattern, decoded),
        PathOp::Regex => cached_regex(pattern)
            .map(|re| re.is_match(decoded))
            .unwrap_or(false),
        PathOp::StartsWith => decoded.starts_with(pattern),
    }
}

/// Apply a string operator.
fn match_str_op(op: &StrOp, value: &str) -> bool {
    match op {
        StrOp::Equals { value: v } => value == v,
        StrOp::Contains { value: v } => value.contains(v),
        StrOp::Regex { pattern } => cached_regex(pattern)
            .map(|re| re.is_match(value))
            .unwrap_or(false),
        StrOp::StartsWith { value: v } => value.starts_with(v),
        StrOp::In { values } => values.iter().any(|v| v == value),
    }
}

/// Minimal glob matcher: `*` matches any sequence, `?` matches one char.
///
/// Used for path globs like `/admin/*`. Case-insensitive to avoid trivial
/// bypass (`/Admin/` vs `/admin/`).
fn glob_match(pattern: &str, path: &str) -> bool {
    let pat = pattern.to_ascii_lowercase();
    let pth = path.to_ascii_lowercase();
    let pat_b = pat.as_bytes();
    let pth_b = pth.as_bytes();
    glob_inner(pat_b, 0, pth_b, 0)
}

fn glob_inner(pat: &[u8], mut pi: usize, pth: &[u8], mut si: usize) -> bool {
    while pi < pat.len() {
        match pat[pi] {
            b'*' => {
                // Collapse consecutive stars.
                while pi < pat.len() && pat[pi] == b'*' {
                    pi += 1;
                }
                if pi == pat.len() {
                    return true;
                }
                while si <= pth.len() {
                    if glob_inner(pat, pi, pth, si) {
                        return true;
                    }
                    si += 1;
                }
                return false;
            }
            b'?' => {
                if si >= pth.len() {
                    return false;
                }
                pi += 1;
                si += 1;
            }
            c => {
                if si >= pth.len() || pth[si] != c {
                    return false;
                }
                pi += 1;
                si += 1;
            }
        }
    }
    si == pth.len()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::event::{HttpData, ProtocolData, SourceKind};
    use std::net::Ipv4Addr;

    fn http_event(path: &str, ip: &str) -> Event {
        Event::new(
            SourceKind::Synthetic,
            ip.parse().unwrap(),
            ProtocolData::Http(HttpData {
                path: path.to_string(),
                ..Default::default()
            }),
        )
    }

    #[test]
    fn ip_cidr_match() {
        assert!(match_ip("10.0.0.0/8", "10.1.2.3".parse().unwrap()));
        assert!(!match_ip("10.0.0.0/8", "11.1.2.3".parse().unwrap()));
    }

    #[test]
    fn ip_range_match() {
        assert!(match_ip(
            "192.168.1.1-192.168.1.100",
            "192.168.1.50".parse().unwrap()
        ));
        assert!(!match_ip(
            "192.168.1.1-192.168.1.100",
            "192.168.1.200".parse().unwrap()
        ));
    }

    #[test]
    fn path_glob_match() {
        let evt = http_event("/admin/users", "1.2.3.4");
        let m = RuleMatch::Path {
            op: PathOp::Glob,
            pattern: "/admin/*".to_string(),
        };
        assert!(m.matches(&evt));
    }

    #[test]
    fn path_regex_case_insensitive() {
        let evt = http_event("/.ENV", "1.2.3.4");
        let m = RuleMatch::Path {
            op: PathOp::Regex,
            pattern: "(?i)\\.env".to_string(),
        };
        assert!(m.matches(&evt));
    }

    #[test]
    fn ruleset_short_circuit_on_allow() {
        let allow_internal = Rule {
            id: "allow-internal".into(),
            name: "allow internal".into(),
            priority: 1,
            enabled: true,
            match_: RuleMatch::Ip {
                cidr: "10.0.0.0/8".into(),
            },
            action: RuleAction::Allow,
            ttl: None,
            source: RuleSource::Config,
            tags: vec![],
            created_at: None,
        };
        let block_env = Rule {
            id: "block-env".into(),
            name: "block .env".into(),
            priority: 2,
            enabled: true,
            match_: RuleMatch::Path {
                op: PathOp::Regex,
                pattern: "(?i)\\.env".into(),
            },
            action: RuleAction::Block,
            ttl: None,
            source: RuleSource::Config,
            tags: vec![],
            created_at: None,
        };
        let rs = RuleSet::new(vec![allow_internal, block_env]);

        // Internal IP hitting .env → should be allowed (short-circuit).
        let evt = Event::new(
            SourceKind::Synthetic,
            IpAddr::V4(Ipv4Addr::new(10, 0, 0, 5)),
            ProtocolData::Http(HttpData {
                path: "/.env".into(),
                ..Default::default()
            }),
        );
        let (rule, short) = rs.evaluate(&evt).expect("should match");
        assert_eq!(rule.id, "allow-internal");
        assert!(short);

        // External IP hitting .env → should hit block rule.
        let evt2 = http_event("/.env", "8.8.8.8");
        let (rule2, short2) = rs.evaluate(&evt2).expect("should match");
        assert_eq!(rule2.id, "block-env");
        assert!(short2);
    }

    #[test]
    fn ruleset_no_match_returns_none() {
        let rs = RuleSet::new(vec![Rule {
            id: "r1".into(),
            name: "r1".into(),
            priority: 1,
            enabled: true,
            match_: RuleMatch::Ip {
                cidr: "10.0.0.0/8".into(),
            },
            action: RuleAction::Block,
            ttl: None,
            source: RuleSource::Config,
            tags: vec![],
            created_at: None,
        }]);
        let evt = http_event("/", "8.8.8.8");
        assert!(rs.evaluate(&evt).is_none());
    }

    #[test]
    fn disabled_rule_skipped() {
        let rs = RuleSet::new(vec![Rule {
            id: "r1".into(),
            name: "r1".into(),
            priority: 1,
            enabled: false,
            match_: RuleMatch::Ip {
                cidr: "0.0.0.0/0".into(),
            },
            action: RuleAction::Block,
            ttl: None,
            source: RuleSource::Config,
            tags: vec![],
            created_at: None,
        }]);
        let evt = http_event("/", "1.2.3.4");
        assert!(rs.evaluate(&evt).is_none());
    }

    #[test]
    fn any_or_all_combinators() {
        let evt = http_event("/admin", "1.2.3.4");
        let m = RuleMatch::All(vec![
            RuleMatch::Path {
                op: PathOp::Equals,
                pattern: "/admin".into(),
            },
            RuleMatch::Any(vec![
                RuleMatch::Ip {
                    cidr: "9.9.9.9".into(),
                },
                RuleMatch::Ip {
                    cidr: "1.2.3.4".into(),
                },
            ]),
        ]);
        assert!(m.matches(&evt));

        let m2 = RuleMatch::All(vec![
            RuleMatch::Path {
                op: PathOp::Equals,
                pattern: "/admin".into(),
            },
            RuleMatch::Not(Box::new(RuleMatch::Ip {
                cidr: "1.2.3.4".into(),
            })),
        ]);
        assert!(!m2.matches(&evt));
    }

    fn rate_rule(count: u32, per_secs: u64, scope: RateScope) -> Rule {
        Rule {
            id: "rate".into(),
            name: "rate".into(),
            priority: 1,
            enabled: true,
            match_: RuleMatch::Rate {
                count,
                per_secs,
                scope,
            },
            action: RuleAction::RateLimit,
            ttl: None,
            source: RuleSource::Config,
            tags: vec![],
            created_at: None,
        }
    }

    #[test]
    fn rate_never_matches_without_backend() {
        let rs = RuleSet::new(vec![rate_rule(1, 60, RateScope::PerIp)]);
        let evt = http_event("/", "1.2.3.4");
        for _ in 0..5 {
            assert!(rs.evaluate(&evt).is_none());
        }
    }

    #[test]
    fn rate_matches_after_threshold_with_backend() {
        let rs = RuleSet::new(vec![rate_rule(3, 60, RateScope::PerIp)]);
        let backend = crate::ratelimit::InMemoryRateLimiter::new();
        let evt = http_event("/", "1.2.3.4");

        assert!(rs.evaluate_with(&evt, Some(&backend)).is_none());
        assert!(rs.evaluate_with(&evt, Some(&backend)).is_none());
        assert!(rs.evaluate_with(&evt, Some(&backend)).is_none());
        let (rule, short) = rs
            .evaluate_with(&evt, Some(&backend))
            .expect("4th hit crosses count=3");
        assert_eq!(rule.id, "rate");
        assert!(short);
    }

    #[test]
    fn rate_scopes_track_independently() {
        let rs = RuleSet::new(vec![rate_rule(1, 60, RateScope::PerPath)]);
        let backend = crate::ratelimit::InMemoryRateLimiter::new();

        let a1 = http_event("/a", "1.1.1.1");
        let a2 = http_event("/a", "2.2.2.2");
        let b1 = http_event("/b", "3.3.3.3");

        assert!(rs.evaluate_with(&a1, Some(&backend)).is_none());
        assert!(rs.evaluate_with(&b1, Some(&backend)).is_none());
        // Second hit on /a (different IP — scope is per path) fires.
        assert!(rs.evaluate_with(&a2, Some(&backend)).is_some());
        // /b still under threshold.
        assert!(rs.evaluate_with(&b1, Some(&backend)).is_some());
    }

    #[test]
    fn rate_per_asn_needs_asn() {
        let m = RuleMatch::Rate {
            count: 1,
            per_secs: 60,
            scope: RateScope::PerAsn,
        };
        let backend = crate::ratelimit::InMemoryRateLimiter::new();
        let evt = http_event("/", "1.2.3.4");
        assert!(!m.matches_with(&evt, Some(&backend)));

        let mut evt2 = http_event("/", "1.2.3.4");
        evt2.asn = Some(1234);
        assert!(!m.matches_with(&evt2, Some(&backend)));
        assert!(m.matches_with(&evt2, Some(&backend)));
    }
}

// Re-export kept for potential external consumers; the value is unused now but
// the function preserves the `HashSet` import path for future indexing work.
#[allow(dead_code)]
fn _ensure_hashset_used() -> std::collections::HashSet<RuleId> {
    std::collections::HashSet::new()
}
