[package]
name = "sentry-cli"
description = "Sentry access monitor CLI"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "sentry"
path = "src/main.rs"

[features]
default = ["tui"]
tui = ["dep:ratatui", "dep:crossterm"]
rate-redis = ["dep:redis"]
onnx = ["sentry-ai/onnx"]
pcap = ["sentry-source-tcp/pcap"]
edge-tls = ["sentry-edge/edge-tls"]
service = ["dep:windows-service"]

[target.'cfg(windows)'.dependencies]
windows-service = { version = "0.7", optional = true }

[dependencies]
sentry-core = { workspace = true }
sentry-storage = { workspace = true }
sentry-ai = { workspace = true }
sentry-geo = { workspace = true }
sentry-reputation = { workspace = true }
sentry-source-nginx = { workspace = true }
sentry-source-syslog = { workspace = true }
sentry-source-cloudflare = { workspace = true }
sentry-source-tcp = { workspace = true }
sentry-edge = { workspace = true }
sentry-action-cloudflare = { workspace = true }
sentry-action-webhook = { workspace = true }
sentry-action-blocklist = { workspace = true }
sentry-action-report = { workspace = true }
sentry-action-firewall = { workspace = true }
sentry-action-opnsense = { workspace = true }
sentry-action-nginx = { workspace = true }

hickory-resolver = { workspace = true }

tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
figment = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
color-eyre = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
ratatui = { workspace = true, optional = true }
crossterm = { workspace = true, optional = true }
prometheus = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
http-body-util = { workspace = true }
redis = { version = "0.27", optional = true, default-features = false, features = ["script"] }
axum = { workspace = true }
argon2 = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }